# TensorFlow basics

In [1]:
# import tensorflow with alias tf 
import tensorflow as tf
print(tf.__version__)

2.4.1


### 1. Creating Tensors

**Create Tensors using tf.constant**

In [2]:
# create a tensor with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# check number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [4]:
# create a vector
vector = tf.constant([10.,10.])
vector

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([10., 10.], dtype=float32)>

In [5]:
# check dimension of vector
vector.ndim

1

In [6]:
# create a matrix
matrix = tf.constant([[1.,2.],
                      [4.,5.]])
matrix

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [4., 5.]], dtype=float32)>

In [7]:
# check dimension of matrix
matrix.ndim

2

In [8]:
# create another matrix
another_matrix = tf.constant([[3.,4.],
                              [4.,5.],
                              [8.,9.]], dtype=tf.float16) # specify the data type
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[3., 4.],
       [4., 5.],
       [8., 9.]], dtype=float16)>

In [9]:
# check dimension of another matrix
another_matrix.ndim

2

In [10]:
# let's create a tensor
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                      [[7,8,9],
                      [10,11,12]],
                     [[13,14,15],
                     [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])>

In [11]:
# check dimension of tensor
tensor.ndim

3

**What we've created so far:**
1. Scalar: a single number  
2. Vector: a number with direction (e.g. wind speed and direction)  
3. Matrix: a 2-dimensional array of numbers   
4. Tensor: an n-dimensional array of numbers (where n can be any number, a 0-dimensional tensor is a scalar and a 1-dimensional tensor is a vector)

**Create Tensors using tf.Variable**

In [12]:
# create the same tensor with tf.Variable() as above
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>)

In [13]:
# let's try to change one of the elements in our changeable tensor
changeable_tensor[0].assign(7)
changeable_tensor # observe that tensor index 0 has been updated to 7

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7])>

In [14]:
# let's try to change one of the elements in our unchangeable tensor
unchangeable_tensor[0].assign(7)
unchangeable_tensor # observe that we can't change the element

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

**Difference between tf.Variable and tf.Constant**  
- tf.Variable allows elements of the tensor to be changed  
- tf.constant does not allow elements of the tensor to be changed  

In practice, need to decide when to use tf.Variable and tf.constant to create tensor

**Creating random tensors**

Random tensors are tensors of some arbitrary size which contain random numbers

In [15]:
# create 2 random (but the same) tensors
random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))

# are they equal?
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

**Shuffle Order of Elements in a Tensor**

In [16]:
# create a tensor first
not_shuffled = tf.constant([[10,7],
                            [3,4],
                            [2,5]])
print(not_shuffled.ndim)
print(not_shuffled)

2
tf.Tensor(
[[10  7]
 [ 3  4]
 [ 2  5]], shape=(3, 2), dtype=int32)


In [17]:
# shuffle a tensor (valuable for when you want to shuffle your data so the inherent order doesn't affect learning)
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed=42) # Randomly shuffles a tensor along its first dimension.

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]])>

**From TensorFlow Documentation**  

Operations that rely on a random seed actually derive it from two seeds: the global and operation-level seeds. This sets the global seed.

Its interactions with operation-level seeds is as follows:

1. If neither the global seed nor the operation seed is set: A randomly picked seed is used for this op.
2. If the global seed is set, but the operation seed is not: The system deterministically picks an operation seed in conjunction with the global seed so that it gets a unique random sequence. Within the same version of tensorflow and user code, this sequence is deterministic. However across different versions, this sequence might change. If the code depends on particular seeds to work, specify both global and operation-level seeds explicitly.
3. If the operation seed is set, but the global seed is not set: A default global seed and the specified operation seed are used to determine the random sequence.
4. If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence.

In [18]:
# scenario 1 - neither global seed nor operation seed is set
not_shuffled = tf.constant([[10,7],
                            [3,4],
                            [2,5]])
tf.random.shuffle(not_shuffled) # result: order always changes, not reproducible

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]])>

In [19]:
# scenario 2 - global seed is set
tf.random.set_seed(42)
not_shuffled = tf.constant([[10,7],
                            [3,4],
                            [2,5]])
tf.random.shuffle(not_shuffled) # result: order doesn't change, reproducible

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]])>

In [20]:
# scenario 3 - global seed is not set but operation seed is set
not_shuffled = tf.constant([[10,7],
                            [3,4],
                            [2,5]])
tf.random.shuffle(not_shuffled, seed=42) # result: order always changes, not reproducible

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]])>

In [21]:
# scenario 4 - global seed and operation seed are set
tf.random.set_seed(7)
not_shuffled = tf.constant([[10,7],
                            [3,4],
                            [2,5]])
tf.random.shuffle(not_shuffled, seed=7) # result: order doesn't change, reproducible

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [10,  7],
       [ 2,  5]])>

**Other ways to make tensors**

In [22]:
# create a tensor of all ones
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [23]:
# create a tensor of all zeros
tf.zeros(shape=(10,7))

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

**create numpy array into tensorflow tensors**

- main difference of numpy arrays and tensorflow tensors is that
- tensors can be run on a GPU (much faster for numerical computing)

In [24]:
import numpy as np
numpy_A = np.arange(1,25, dtype=np.int32)  # create a Numpy array between 1 to 25
numpy_A
 
# X = tf.constant(some_matrix) # capital for matrix or tensor
# y = tf.constant(vector) # lower case for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [25]:
numpy_A.shape

(24,)

In [26]:
# pass numpy array to tf.constant and reshape
A = tf.constant(numpy_A, shape=(2,3,4)) # shape: 2*3*4 = 24 (total number of elements in the array)
B = tf.constant(numpy_A)
A, B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24])>)

### 2. Getting Information from Tensor 

- Shape (tensor.shape) : the size / the length / the number of elements of the tensor along each of its axes.  
- Rank (tensor.ndim) : the number of tensor dimensions. As scalar has rank 0, a vector has rank 1, a matrix has rank 2 and a tensor has rank n  
- Axis or dimension (tensor[0], tensor[:,1]) : a particular dimension of a tensor  
- Size (tf.size) : the total number of items in the tensor

In [27]:
# create a rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros(shape=(2,3,4,5))
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [28]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [29]:
# get various attributes of our tensor
print('Datatype of every element:', rank_4_tensor.dtype)
print('Number of dimensions (rank):', rank_4_tensor.ndim)
print('Shape of tensor:', rank_4_tensor.shape)
print('Elements along the 0 axis:', rank_4_tensor.shape[0])
print('Elements along the last axis:', rank_4_tensor.shape[-1])
print('Total number of elements in our tensor:', tf.size(rank_4_tensor))
print('Total number of elements in our tensor:', tf.size(rank_4_tensor).numpy()) # adding .numpy() will help to convert it into number

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along the 0 axis: 2
Elements along the last axis: 5
Total number of elements in our tensor: tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in our tensor: 120


### 3. Indexing Tensors 

Tensors can be indexed just like Python lists.

In [30]:
some_list = [1,2,3,4]
some_list[:2]

[1, 2]

In [31]:
# get the first 2 elements of each dimension
rank_4_tensor[:2,:2,:2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [32]:
# get first element from each dimension except for the final one
rank_4_tensor[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [33]:
# get first element from each dimension except for the second final one
rank_4_tensor[:1,:1,:,:1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

## 4. Expanding Tensor

In [34]:
# create a rank 2 tensor (i.e. 2 dimension)
rank_2_tensor = tf.constant([[10,7],
                            [3,4]])
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [35]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

In [36]:
# get the last item of each of row of our rank 2 tensor
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4])>

In [37]:
# Add in extra dimension to our rank 2 tensor but keeping the same info
rank_3_tensor = rank_2_tensor[..., tf.newaxis] # ..., implies every access of previous exist. 
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]])>

In [38]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis=-1) # '-1' means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]])>

In [39]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis=0) # expand 0 axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]])>

In [40]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis=1) # expand on axis 1

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[10,  7]],

       [[ 3,  4]]])>

In [41]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

## 5. Manipulating tensor (tensor operation)

**Basic Operations (element-wise operation)**

`+`, `-`, `*`, `/`

In [42]:
# You can add values to a tensor using the addition operation
tensor = tf.constant([[10,7],
                     [3,4]])

tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]])>

In [43]:
# original tensor is unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

In [44]:
# if we want to change the tensor 
# tensor  = tensor + 10
# tensor

In [45]:
# multiplication also works
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]])>

In [46]:
# subtraction also works
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]])>

In [47]:
# we can use tensorflow built-in function 
tf.multiply(tensor, 10) 

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]])>

In [48]:
# divide also works
tf.divide(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1. , 0.7],
       [0.3, 0.4]])>

**Matrix Multiplication** 

In machine learning, matrix multiplication is one of the most common tensor operations.  

There are two rules our tensors (or matrices) need to fulfil if we're going to matrix multiply them:  
1. the linear dimension must match   
2. the resulting matrix has the shape of the inner dimension

In [49]:
# Matrix Multiplication in Tensorflow - tensor shapes must align for this to work
print(tensor)
tf.matmul(tensor, tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]])>

In [50]:
# matrix multiplication with python operator "@"
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]])>

In [51]:
# practice creating two tensors and apply matmul
a = tf.constant([[1,2,5],
                [7,2,1],
                [3,3,3]])
b = tf.constant([[3,5],
                [6,7],
                [1,8]])
tf.matmul(a,b)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]])>

In [52]:
# example on matmul failing
X = tf.constant([[1,2],
                [3,4],
                [5,6]])
Y = tf.constant([[7,8],
                [9,10],
                [11,12]])
print(X.shape)
print(Y.shape)
tf.matmul(X, Y) # this will return an error as tensor shapes are not aligned

(3, 2)
(3, 2)


InvalidArgumentError: Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2] [Op:MatMul]

In [53]:
# try to align the shapes using transpose so that matmul can work
tf.matmul(X, tf.transpose(Y)) 

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]])>

In [54]:
# alternatively use reshape to change the shape of Y
X @ tf.reshape(Y, shape=(2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]])>

**The dot product**

Matrix multiplication is also referred to as the dot product.  

You can perform matrix multiplication using:  
    - `tf.matmul()`   
    - `tf.tensordot()`

In [55]:
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]])>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]])>)

In [56]:
# transpose X
tf.tensordot(tf.transpose(X), Y, axes =1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]])>

In [57]:
# perform matrix multiplication between X and Y (transposed)
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]])>

In [58]:
# perform matrix multiplication between X and Y (reshaped)
tf.matmul(X, tf.reshape(Y, shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]])>

In [59]:
# check the values of Y, reshaped Y and transposed Y
print('Normal Y:')
print(Y, '\n')

print('Reshaped Y:')
print(tf.reshape(Y, shape=(2,3)), '\n')

print('Transposed Y:')
print(tf.transpose(Y))

Normal Y:
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Reshaped Y:
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Transposed Y:
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


Generally when perform matrix multiplication on two tensors and one of the axes doesn't line up, you will transpose rather than reshape one of the tensors to satify the matrix multiplication rules

## 6. Changing the datatype of a tensor

In [60]:
# create a new tensor with default datatype (float32)
B =tf.constant([1.7,7.4])
B.dtype

tf.float32

In [61]:
c = tf.constant([7,10])
c.dtype

tf.int32

In [62]:
# change from float32 to float16 --> reduced precision and half the memory and hence, increase speed
B = tf.cast(B, dtype=tf.float16)
B

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>

In [63]:
# change from int32 to float 32
c = tf.cast(c, dtype=tf.float32)
c

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 7., 10.], dtype=float32)>

In [64]:
c = tf.cast(c, dtype=tf.float16)
c

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([ 7., 10.], dtype=float16)>

## 7. Aggregating Tensors

Aggregating tensors = condensing them from multiple values down to a smaller amount of values.

In [65]:
# Create a new tensor
D = tf.constant([-7,-10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10])>

In [66]:
# Get the absolute values
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10])>

Let's go through the following forms of aggregation:  
- Get the minimum  
- Get the maximum  
- Get the mean of a tensor  
- Get the sum of a tensor

In [67]:
# Create a random tensor with values between 0 and 100 of size 50
E = tf.constant(np.random.randint(0,100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([16, 84, 11, 42, 56, 81, 45, 15, 81, 94, 34, 69, 40, 47, 79, 39, 75,
       37, 34, 56, 84, 68, 89, 65, 48, 77, 85, 51, 34, 62,  4,  3, 53, 66,
       91, 18, 13, 98, 93, 92, 11, 89, 69, 83, 66, 22, 50, 82, 82, 84])>

In [68]:
tf.size(E), E.ndim, E.shape

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, 1, TensorShape([50]))

In [69]:
# Find the minimum of a tensor
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [70]:
# find the maximum of a tensor
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int32, numpy=98>

In [71]:
# find the mean of a tensor
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int32, numpy=57>

In [72]:
# find the sum of a tensor
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int32, numpy=2867>

In [73]:
# find the variance of a tensor (note, tensor must be real or complex number)
E = tf.cast(E, dtype=tf.float32)
tf.math.reduce_variance(E)

<tf.Tensor: shape=(), dtype=float32, numpy=760.46436>

In [74]:
# find the std deviation of a tensor (note, tensor must be real or complex number)
tf.math.reduce_std(E)

<tf.Tensor: shape=(), dtype=float32, numpy=27.576519>

## 8. Find the positional maximum and minimum

In [75]:
# Create a new tensor for finding positional minimum and maximum
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [76]:
# get the position of the max element in tensor
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [77]:
# index on our largest value position
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [78]:
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [79]:
# check for equality
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [80]:
# get the position of the minimum element in tensor
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [81]:
# check minimum value using positional min index
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [82]:
# check for equality between the value obtained from the index position and the min
F[tf.argmin(F)] == tf.reduce_min(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

## 9. Squeezing a tensor (removing all single dimensions)

In [83]:
# create a tensor to get started
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
           0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256,
           0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ,
           0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ,
           0.13803864, 0.12217975, 0.5754491 , 0.9417181 , 0.9186585 ,
           0.59708476, 0.6109482 , 0.82086265, 0.83269787, 0.8915849 ,
           0.01377225, 0.49807465, 0.57503664, 0.6856195 , 0.75972784,
           0.908944  , 0.40900218, 0.8765154 , 0.53890026, 0.42733097,
           0.401173  , 0.66623247, 0.16348064, 0.18220246, 0.97040176,
           0.06139731, 0.53034747, 0.9869994 , 0.4746945 , 0.8646754 ]]]]],
      dtype=float32)>

In [84]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [85]:
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
        0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256,
        0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ,
        0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ,
        0.13803864, 0.12217975, 0.5754491 , 0.9417181 , 0.9186585 ,
        0.59708476, 0.6109482 , 0.82086265, 0.83269787, 0.8915849 ,
        0.01377225, 0.49807465, 0.57503664, 0.6856195 , 0.75972784,
        0.908944  , 0.40900218, 0.8765154 , 0.53890026, 0.42733097,
        0.401173  , 0.66623247, 0.16348064, 0.18220246, 0.97040176,
        0.06139731, 0.53034747, 0.9869994 , 0.4746945 , 0.8646754 ],
       dtype=float32)>,
 TensorShape([50]))

In [86]:
G_squeezed.ndim

1

In [87]:
# create a tensor to get started
G_another = tf.constant(tf.random.uniform(shape=[24]), shape=(1,2,3,4))
G_another

<tf.Tensor: shape=(1, 2, 3, 4), dtype=float32, numpy=
array([[[[0.7413678 , 0.62854624, 0.01738465, 0.3431449 ],
         [0.51063764, 0.3777541 , 0.07321596, 0.02137029],
         [0.2871771 , 0.4710616 , 0.6936141 , 0.07321334]],

        [[0.93251204, 0.20843053, 0.70105827, 0.45856392],
         [0.8596262 , 0.92934334, 0.20291913, 0.76865506],
         [0.60016024, 0.27039742, 0.88180614, 0.05365038]]]],
      dtype=float32)>

In [88]:
# squeeze the tensor
G_another_sq = tf.squeeze(G_another)
G_another_sq, G_another_sq.shape

(<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
 array([[[0.7413678 , 0.62854624, 0.01738465, 0.3431449 ],
         [0.51063764, 0.3777541 , 0.07321596, 0.02137029],
         [0.2871771 , 0.4710616 , 0.6936141 , 0.07321334]],
 
        [[0.93251204, 0.20843053, 0.70105827, 0.45856392],
         [0.8596262 , 0.92934334, 0.20291913, 0.76865506],
         [0.60016024, 0.27039742, 0.88180614, 0.05365038]]], dtype=float32)>,
 TensorShape([2, 3, 4]))

In [89]:
# get back the original shape using expand dims
G_another_org = tf.expand_dims(G_another_sq, axis=0) # expand on axis 0
G_another_org.shape

TensorShape([1, 2, 3, 4])

## 10. One-hot encoding tensors

In [90]:
# create a list of indices
some_list = [0,1,2,3] # could be red, green, blue, purple

# one hot encode our list of indices
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [91]:
# Specify custom values for one hot encoding
tf.one_hot(some_list, depth=4, on_value='have fun', off_value='not fun')


<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'have fun', b'not fun', b'not fun', b'not fun'],
       [b'not fun', b'have fun', b'not fun', b'not fun'],
       [b'not fun', b'not fun', b'have fun', b'not fun'],
       [b'not fun', b'not fun', b'not fun', b'have fun']], dtype=object)>

## 11. Squaring, log, square root

In [92]:
# create a new tensor
H = tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [93]:
# square it
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>

In [94]:
# square root (tensor has to have appropriate dtype)
tf.sqrt(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [95]:
# Find the log (tensor has to have appropriate dtype)
tf.math.log(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### 12. Tensors and NumPy

TensorFlow interacts beautifully with NumPy arrays.

In [96]:
# Create a tensor directly from a NumPy array
J = tf.constant(np.array([3.,7.,10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [97]:
# Convert our tensor back to NumPy array
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [98]:
# Convert tensor J to a NumPy array
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [99]:
J = tf.constant([3.])
J.numpy()[0]

3.0

In [100]:
# The defult types of each are slightly different
numpy_J = tf.constant(np.array([3.,7.,10.]))
tensor_J = tf.constant([3.,7.,10.])

# check the datatypes of each (note the difference)
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

## 13 Checkpoint to test learnings

a. Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().  
b. Find the shape, rank and size of the tensors you created in 1.  
c. Create two tensors containing random values between 0 and 1 with shape [5, 300].  
d. Multiply the two tensors you created in 3 using matrix multiplication.  
e. Multiply the two tensors you created in 3 using dot product.  
f. Create a tensor with random values between 0 and 1 with shape [224, 224, 3].  
g. Find the min and max values of the tensor you created in 6.  
h. Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].  
i. Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.  
j. One-hot encode the tensor you created in 9.  

In [103]:
# a. create a vector, scalar, matrix and tensor with values of your choosing using tf.constant()
tensor_vec = tf.constant([1.,2.,3.])
tensor_sca = tf.constant(49.)
tensor_mat = tf.constant([[1.,2.,3.],
                         [4.,5.,6.],
                         [7.,8.,9]])
tensor_ten = tf.constant([[[1.,2.,3.],[4.,5.,6.]],
                         [[7.,8.,9.], [10.,11.,12.]]])

print('tensor vector:', tensor_vec)
print('\ntensor scalar:', tensor_sca)
print('\ntensor matrix:', tensor_mat)
print('\ntensor:', tensor_ten)

tensor vector: tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)

tensor scalar: tf.Tensor(49.0, shape=(), dtype=float32)

tensor matrix: tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]], shape=(3, 3), dtype=float32)

tensor: tf.Tensor(
[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]], shape=(2, 2, 3), dtype=float32)


In [104]:
# b. find the shape, rank and size of the tensors you created in a.
print('Scalar:')
print('shape:', tensor_sca.shape)
print('rank:', tensor_sca.ndim)
print('size:', tf.size(tensor_sca))

print('\nVector:')
print('shape:', tensor_vec.shape)
print('rank:', tensor_vec.ndim)
print('size:', tf.size(tensor_vec))

print('\nMatrix:')
print('shape:', tensor_mat.shape)
print('rank:', tensor_mat.ndim)
print('size:', tf.size(tensor_mat))

print('\nTensor:')
print('shape:', tensor_ten.shape)
print('rank:', tensor_ten.ndim)
print('size:', tf.size(tensor_ten))



Scalar:
shape: ()
rank: 0
size: tf.Tensor(1, shape=(), dtype=int32)

Vector:
shape: (3,)
rank: 1
size: tf.Tensor(3, shape=(), dtype=int32)

Matrix:
shape: (3, 3)
rank: 2
size: tf.Tensor(9, shape=(), dtype=int32)

Tensor:
shape: (2, 2, 3)
rank: 3
size: tf.Tensor(12, shape=(), dtype=int32)


In [105]:
# c. Create two tensors containing random values between 0 and 1 with shape [5, 300].

tensor_1 = tf.random.uniform(shape=[5,300], minval=0, maxval=1, dtype=tf.float32)
tensor_2 = tf.random.uniform(shape=[5,300], minval=0, maxval=1, dtype=tf.float32)

tensor_1, tensor_2

(<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.7402308 , 0.33938193, 0.5692506 , ..., 0.08656633, 0.19666708,
         0.7110305 ],
        [0.13257599, 0.81292987, 0.01284087, ..., 0.02695906, 0.2927854 ,
         0.06227863],
        [0.282601  , 0.47868013, 0.77569485, ..., 0.28239357, 0.632112  ,
         0.44452012],
        [0.02029276, 0.7841259 , 0.16919017, ..., 0.26143157, 0.43055534,
         0.47421408],
        [0.2616079 , 0.00913954, 0.20257103, ..., 0.3548187 , 0.9939178 ,
         0.35239196]], dtype=float32)>,
 <tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.803156  , 0.49777734, 0.37054038, ..., 0.42893624, 0.49179256,
         0.39297235],
        [0.14517438, 0.72666824, 0.80103934, ..., 0.832801  , 0.649397  ,
         0.29312778],
        [0.4216962 , 0.6768439 , 0.5627917 , ..., 0.56929183, 0.90308595,
         0.31530714],
        [0.6198498 , 0.70206463, 0.994668  , ..., 0.03745186, 0.23192072,
         0.23984468],
        [0.01790

In [109]:
# d. Multiply the two tensors you created in 3 using matrix multiplication.
tf.matmul(tensor_1, tf.transpose(tensor_2))

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[72.34169 , 73.843315, 71.9973  , 69.78643 , 68.59812 ],
       [76.299805, 75.77641 , 71.65502 , 72.104355, 75.29942 ],
       [72.80916 , 75.74101 , 71.199   , 73.04656 , 71.714485],
       [74.654816, 76.64436 , 73.32848 , 72.21242 , 73.30908 ],
       [77.44371 , 78.68228 , 71.98375 , 72.70096 , 72.917274]],
      dtype=float32)>

In [113]:
# e. Multiply the two tensors you created in 3 using dot product.
tf.tensordot(tensor_1, tf.transpose(tensor_2), axes=1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[72.34169 , 73.843315, 71.9973  , 69.78643 , 68.59812 ],
       [76.299805, 75.77641 , 71.65502 , 72.104355, 75.29942 ],
       [72.80916 , 75.74101 , 71.199   , 73.04656 , 71.714485],
       [74.654816, 76.64436 , 73.32848 , 72.21242 , 73.30908 ],
       [77.44371 , 78.68228 , 71.98375 , 72.70096 , 72.917274]],
      dtype=float32)>

In [114]:
# f. Create a tensor with random values between 0 and 1 with shape [224, 224, 3].
tensor_rand = tf.random.uniform(shape=(224,224,3), minval=0, maxval=1)
tensor_rand

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.95831835, 0.01680839, 0.3156035 ],
        [0.16013157, 0.7148702 , 0.7892921 ],
        [0.11484027, 0.33310425, 0.21091413],
        ...,
        [0.6279857 , 0.85051286, 0.9490392 ],
        [0.62438786, 0.2802421 , 0.18754554],
        [0.9087832 , 0.46846092, 0.5317346 ]],

       [[0.85744655, 0.51288927, 0.18603599],
        [0.04882693, 0.78045344, 0.79377043],
        [0.9356363 , 0.32798207, 0.15949786],
        ...,
        [0.6933085 , 0.5420611 , 0.1860913 ],
        [0.7326596 , 0.9234495 , 0.07200372],
        [0.5471792 , 0.24985266, 0.14673471]],

       [[0.5033684 , 0.7000841 , 0.21468806],
        [0.9304948 , 0.17212296, 0.720364  ],
        [0.6657183 , 0.17304075, 0.7110392 ],
        ...,
        [0.35423398, 0.126225  , 0.24436975],
        [0.096439  , 0.06387579, 0.32836854],
        [0.15067935, 0.6084572 , 0.47766674]],

       ...,

       [[0.23573959, 0.42224514, 0.9151635 ],
        [0.38

In [117]:
# g. Find the min and max values of the tensor you created in 6.
print('min value of the tensor:', tf.reduce_min(tensor_rand).numpy())
print('max value of the tensor:', tf.reduce_max(tensor_rand).numpy())

min value of the tensor: 1.1444092e-05
max value of the tensor: 0.99999726


In [118]:
# h. Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].
tensor_rand2 = tf.random.uniform(shape=[1,224,224,3])
tensor_rand2_sq = tf.squeeze(tensor_rand2)
tensor_rand2_sq.shape

TensorShape([224, 224, 3])

In [119]:
# i. Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.
tensor_n = tf.constant([1.,2.,3.,4.,5.,6.,7.,8.,9.,10.])
print('Positional Index with maximum value:', tf.argmax(tensor_n))
print('largest value of tensor:', tensor_n[tf.argmax(tensor_n)])

Positional Index with maximum value: tf.Tensor(9, shape=(), dtype=int64)
largest value of tensor: tf.Tensor(10.0, shape=(), dtype=float32)


In [125]:
# j. One-hot encode the tensor you created in 9.
tf.one_hot(tf.cast(tensor_n, dtype=tf.int32), depth=10)

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>